use std::{
    collections::{HashMap, HashSet},
    path::PathBuf,
    sync::{
        Arc, Weak,
        atomic::{AtomicU64, Ordering},
    },
    time::{Instant, SystemTime, UNIX_EPOCH},
};

use directories::ProjectDirs;
use display_info::DisplayInfo;
use parking_lot::{Mutex, RwLock};
use sha2::{Digest, Sha256};
use tauri::{AppHandle, Emitter, Manager};
use tokio::sync::mpsc;
use uuid::Uuid;

use crate::{
    config::{AppConfig, TrustedPeerConfig},
    crypto::generate_static_keypair,
    input::{
        InputBridge, NativeInputEvent, PlatformPermission, hid_to_key_name, key_name_to_hid,
        open_permission_settings as open_native_permission_settings, query_permission,
    },
    model::{
        ActivityLog, AppSnapshot, DeviceId, DeviceInfo, LogLevel, OsKind, PeerInfo, PeerStatus,
        PermissionState, ScreenInfo, ServiceStatus, SharingSettings,
    },
    network::{ConnectionMetadata, LocalNode, NetworkEvent, NetworkService},
    protocol::{
        ButtonInput, ButtonState, CanonicalKeyCode, ControlClaim, ControlLease, Focus, HidKeyCode,
        Input, InputEvent, KeyInput, KeyModifiers, KeyState, Layout, LayoutPlacement, Message,
        PairApproval, PairReject, PairRequest, Platform, PointerButton, PointerMoveNormalized,
        ScreenDescriptor, Screens, WheelInput, WheelUnit, WireMessage,
    },
    topology::{Direction, PointerPosition, ScreenTopology, ScreenTransition},
};

const SNAPSHOT_EVENT: &str = "snapshot://updated";
const MAX_LOG_ENTRIES: usize = 120;
const CONTROL_LEASE_MS: u32 = 5_000;

#[derive(Debug, Clone, Copy)]
struct NativeScreenBounds {
    x: i32,
    y: i32,
    width: u32,
    height: u32,
}

impl NativeScreenBounds {
    fn contains(&self, x: f64, y: f64) -> bool {
        x >= f64::from(self.x)
            && x < f64::from(self.x) + f64::from(self.width)
            && y >= f64::from(self.y)
            && y < f64::from(self.y) + f64::from(self.height)
    }
}

#[derive(Debug, Clone)]
struct PairSession {
    connection_id: Uuid,
    /// Request identifier generated by this endpoint. A valid remote approval
    /// must echo this value, so approvals cannot be reused across connections.
    request_id: String,
    /// Request identifier generated by the peer. Our approval echoes this ID.
    remote_request_id: Option<String>,
    remote_static_key: [u8; 32],
    local_approved: bool,
    remote_approved: bool,
}

#[derive(Debug)]
struct EdgeAttempt {
    from_screen_id: String,
    to_screen_id: String,
    direction: Direction,
    started_at: Instant,
    travel_px: f64,
}

#[derive(Debug)]
struct ControlState {
    generation: u64,
    holder: DeviceId,
    lease_id: String,
    input_set_id: String,
    sequence: u64,
    pointer: Option<PointerPosition>,
    last_native_pointer: Option<(f64, f64)>,
    pressed_hid: HashSet<u16>,
    claim_announced: bool,
    last_remote_sequence: u64,
    edge_attempt: Option<EdgeAttempt>,
    pointer_parking: Option<(f64, f64)>,
    remote_pressed_keys: HashSet<String>,
    remote_pressed_buttons: HashSet<String>,
}

impl ControlState {
    fn new(local_id: DeviceId, primary_screen: Option<&ScreenInfo>) -> Self {
        let generation = unix_millis();
        Self {
            generation,
            holder: local_id,
            lease_id: format!("{generation:020}:{local_id}"),
            input_set_id: format!("physical:{local_id}"),
            sequence: 0,
            pointer: primary_screen.map(|screen| {
                PointerPosition::new(
                    screen.id.clone(),
                    f64::from(screen.width) / 2.0,
                    f64::from(screen.height) / 2.0,
                )
            }),
            last_native_pointer: None,
            pressed_hid: HashSet::new(),
            claim_announced: false,
            last_remote_sequence: 0,
            edge_attempt: None,
            pointer_parking: None,
            remote_pressed_keys: HashSet::new(),
            remote_pressed_buttons: HashSet::new(),
        }
    }

    fn next_sequence(&mut self) -> u64 {
        self.sequence = self.sequence.saturating_add(1);
        self.sequence
    }
}

pub struct AppCore {
    app: AppHandle,
    config_path: PathBuf,
    config: RwLock<AppConfig>,
    snapshot: RwLock<AppSnapshot>,
    topology: RwLock<ScreenTopology>,
    native_screens: RwLock<HashMap<String, NativeScreenBounds>>,
    network: Mutex<Option<NetworkService>>,
    pair_sessions: RwLock<HashMap<DeviceId, PairSession>>,
    layout_revision: AtomicU64,
    remote_layout_revisions: RwLock<HashMap<DeviceId, u64>>,
    control: Mutex<ControlState>,
    input: Arc<InputBridge>,
}

impl AppCore {
    pub fn load(app: AppHandle) -> Result<Arc<Self>, String> {
        let config_path = config_path()?;
        let mut config = AppConfig::load_or_create_with(&config_path, || {
            let keypair = generate_static_keypair()
                .expect("the operating system random source must generate a Noise key");
            AppConfig::new(Uuid::new_v4(), keypair.private)
        })
        .map_err(|error| error.to_string())?;

        let device_name = hostname::get()
            .ok()
            .and_then(|name| name.into_string().ok())
            .filter(|name| !name.trim().is_empty())
            .unwrap_or_else(|| "This computer".into());
        let local_device = DeviceInfo {
            id: config.device_id,
            name: device_name,
            os: OsKind::current(),
            version: os_version(),
        };
        let (mut topology, native_screens) = enumerate_local_screens(&local_device)?;
        if migrate_legacy_windows_placements(&mut config, &topology) {
            config
                .save_atomic(&config_path)
                .map_err(|error| error.to_string())?;
        }
        topology.apply_placements(&config.screen_layout);
        let primary = topology
            .screens()
            .iter()
            .find(|screen| screen.primary && screen.is_available())
            .or_else(|| {
                topology
                    .screens()
                    .iter()
                    .find(|screen| screen.is_available())
            });
        let control = ControlState::new(config.device_id, primary);
        let permission = permission_state(query_permission());
        let snapshot = AppSnapshot {
            local_device: local_device.clone(),
            service_status: ServiceStatus::Stopped,
            sharing_enabled: false,
            active_controller_id: config.device_id,
            active_screen_id: control
                .pointer
                .as_ref()
                .map(|pointer| pointer.screen_id.clone()),
            listen_port: None,
            permission,
            screens: topology.screens().to_vec(),
            peers: Vec::new(),
            settings: config.settings.clone(),
            logs: vec![ActivityLog {
                id: Uuid::new_v4().to_string(),
                timestamp: unix_millis(),
                level: LogLevel::Info,
                message: "InputMesh 已就绪，正在启动局域网发现".into(),
            }],
        };

        Ok(Arc::new(Self {
            app,
            config_path,
            config: RwLock::new(config),
            snapshot: RwLock::new(snapshot),
            topology: RwLock::new(topology),
            native_screens: RwLock::new(native_screens),
            network: Mutex::new(None),
            pair_sessions: RwLock::new(HashMap::new()),
            layout_revision: AtomicU64::new(unix_millis()),
            remote_layout_revisions: RwLock::new(HashMap::new()),
            control: Mutex::new(control),
            input: InputBridge::new(),
        }))
    }

    pub async fn start_network(self: &Arc<Self>) -> Result<(), String> {
        if self.network.lock().is_some() {
            return Ok(());
        }
        self.update_snapshot(|snapshot| snapshot.service_status = ServiceStatus::Starting);
        let (events_tx, mut events_rx) = mpsc::unbounded_channel();
        let local = {
            let snapshot = self.snapshot.read();
            let config = self.config.read();
            LocalNode {
                device_id: snapshot.local_device.id.to_string(),
                name: snapshot.local_device.name.clone(),
                platform: match snapshot.local_device.os {
                    OsKind::Windows => Platform::Windows,
                    _ => Platform::Macos,
                },
                os_version: snapshot.local_device.version.clone(),
                app_version: env!("CARGO_PKG_VERSION").into(),
                private_key: config.noise_static_private_key,
                preferred_port: config.listen_port,
            }
        };
        match NetworkService::start(local, events_tx).await {
            Ok(service) => {
                let port = service.port();
                *self.network.lock() = Some(service);
                self.update_snapshot(|snapshot| {
                    snapshot.service_status = ServiceStatus::Running;
                    snapshot.listen_port = Some(port);
                });
                self.add_log(LogLevel::Info, format!("局域网服务已启动，端口 {port}"));

                let weak = Arc::downgrade(self);
                tauri::async_runtime::spawn(async move {
                    while let Some(event) = events_rx.recv().await {
                        let Some(core) = weak.upgrade() else {
                            break;
                        };
                        core.handle_network_event(event);
                    }
                });
                Ok(())
            }
            Err(error) => {
                self.update_snapshot(|snapshot| snapshot.service_status = ServiceStatus::Error);
                self.add_log(LogLevel::Error, format!("局域网服务启动失败：{error}"));
                Err(error)
            }
        }
    }

    pub fn snapshot(&self) -> AppSnapshot {
        let permission = permission_state(query_permission());
        let mut snapshot = self.snapshot.write();
        snapshot.permission = permission;
        snapshot.clone()
    }

    pub fn set_sharing_enabled(self: &Arc<Self>, enabled: bool) -> Result<AppSnapshot, String> {
        if enabled {
            let permission = query_permission();
            if permission.requires_action {
                self.update_snapshot(|snapshot| {
                    snapshot.permission = permission_state(permission.clone())
                });
                return Err(permission.help_text);
            }
            let weak: Weak<Self> = Arc::downgrade(self);
            let emergency_weak = weak.clone();
            self.input.install(
                Arc::new(move |event| {
                    weak.upgrade()
                        .is_some_and(|core| core.handle_local_input(event))
                }),
                Arc::new(move || {
                    if let Some(core) = emergency_weak.upgrade() {
                        core.on_emergency_release();
                    }
                }),
            )?;
        }
        if !enabled {
            let lease_id = self.control.lock().lease_id.clone();
            self.broadcast(WireMessage::new(Message::ControlRelease(
                crate::protocol::ControlRelease { lease_id },
            )));
            self.release_remote_inputs();
            self.reset_control_to_local();
        }
        self.input.set_enabled(enabled);
        let mut next_config = self.config.read().clone();
        next_config.sharing_enabled = enabled;
        if let Err(error) = next_config.save_atomic(&self.config_path) {
            if enabled {
                self.input.set_enabled(false);
            }
            self.update_snapshot(|snapshot| snapshot.sharing_enabled = false);
            return Err(error.to_string());
        }
        *self.config.write() = next_config;
        self.update_snapshot(|snapshot| snapshot.sharing_enabled = enabled);
        self.add_log(
            LogLevel::Info,
            if enabled {
                "键鼠共享已开启；Ctrl + Alt + Esc 可紧急释放"
            } else {
                "键鼠共享已停止"
            },
        );
        tracing::info!(enabled, "input sharing state changed");
        Ok(self.snapshot())
    }

    pub fn set_screen_enabled(
        &self,
        screen_id: &str,
        enabled: bool,
    ) -> Result<AppSnapshot, String> {
        let mut topology = self.topology.read().clone();
        let target = topology
            .screen(screen_id)
            .cloned()
            .ok_or_else(|| format!("找不到屏幕 {screen_id}"))?;
        if !enabled
            && topology
                .screens()
                .iter()
                .filter(|screen| {
                    screen.owner_device_id == target.owner_device_id && screen.is_available()
                })
                .count()
                <= 1
        {
            return Err("每台设备至少要保留一块屏幕参与键鼠共享".into());
        }
        topology
            .set_screen_enabled(screen_id, enabled)
            .map_err(|error| error.to_string())?;
        topology.normalize_origin();
        self.commit_topology(topology)?;
        self.broadcast_layout();
        Ok(self.snapshot())
    }

    pub fn update_screen_position(
        &self,
        screen_id: &str,
        x: i32,
        y: i32,
    ) -> Result<AppSnapshot, String> {
        let mut topology = self.topology.read().clone();
        topology
            .set_screen_position(screen_id, x, y)
            .map_err(|error| error.to_string())?;
        topology
            .snap_screen_to_nearest_edge(screen_id)
            .map_err(|error| error.to_string())?;
        topology.normalize_origin();
        self.commit_topology(topology)?;
        self.broadcast_layout();
        Ok(self.snapshot())
    }

    pub fn update_settings(&self, settings: SharingSettings) -> Result<AppSnapshot, String> {
        validate_settings(&settings)?;
        let mut next_config = self.config.read().clone();
        next_config.settings = settings.clone();
        next_config
            .save_atomic(&self.config_path)
            .map_err(|error| error.to_string())?;
        *self.config.write() = next_config;
        self.update_snapshot(|snapshot| snapshot.settings = settings);
        Ok(self.snapshot())
    }

    pub fn approve_peer(&self, peer_id: DeviceId) -> Result<AppSnapshot, String> {
        let (session, peer) = {
            let sessions = self.pair_sessions.read();
            let session = sessions
                .get(&peer_id)
                .cloned()
                .ok_or_else(|| "找不到待配对会话，请等待设备重新连接".to_string())?;
            let peer = self
                .snapshot
                .read()
                .peers
                .iter()
                .find(|peer| peer.id == peer_id)
                .cloned()
                .ok_or_else(|| "找不到该设备".to_string())?;
            (session, peer)
        };

        let trusted = TrustedPeerConfig {
            device_id: peer_id,
            name: peer.name.clone(),
            noise_static_public_key: session.remote_static_key,
            fingerprint: fingerprint(&session.remote_static_key),
            trusted_at: unix_millis(),
            last_seen_at: Some(unix_millis()),
            last_known_address: peer.address.clone(),
        };
        self.config.write().upsert_trusted_peer(trusted);
        self.persist_config()?;
        let remote_request_id = if let Some(current) = self.pair_sessions.write().get_mut(&peer_id)
        {
            current.local_approved = true;
            current.remote_request_id.clone()
        } else {
            None
        };
        if let Some(request_id) = remote_request_id {
            self.send_pair_approval(peer_id, request_id)?;
        }
        self.refresh_peer_trust_status(peer_id);
        self.add_log(LogLevel::Info, format!("已允许设备 {}", peer.name));
        Ok(self.snapshot())
    }

    pub fn reject_peer(&self, peer_id: DeviceId) -> Result<AppSnapshot, String> {
        if let Some(session) = self.pair_sessions.read().get(&peer_id).cloned()
            && let Some(request_id) = session.remote_request_id
        {
            let _ = self.send_to(
                peer_id,
                WireMessage::new(Message::PairReject(PairReject {
                    request_id,
                    reason: Some("用户已断开并取消信任".into()),
                })),
            );
        }
        self.config.write().remove_trusted_peer(peer_id);
        self.persist_config()?;
        self.update_peer(peer_id, |peer| {
            peer.status = PeerStatus::Offline;
            peer.pairing_code = None;
        });
        if let Some(network) = self.network.lock().as_ref() {
            network.disconnect(&peer_id.to_string(), "pairing rejected");
        }
        self.add_log(LogLevel::Warning, format!("已拒绝设备 {peer_id}"));
        Ok(self.snapshot())
    }

    pub fn open_permission_settings(&self) -> Result<AppSnapshot, String> {
        open_native_permission_settings()?;
        self.update_snapshot(|snapshot| snapshot.permission = permission_state(query_permission()));
        Ok(self.snapshot())
    }

    pub fn refresh_discovery(&self) -> AppSnapshot {
        self.add_log(LogLevel::Info, "正在持续扫描局域网设备");
        self.snapshot()
    }

    fn handle_network_event(&self, event: NetworkEvent) {
        match event {
            NetworkEvent::Discovered(record) => self.on_discovered(record),
            NetworkEvent::DiscoveryRemoved { device_id } => {
                if let Ok(id) = Uuid::parse_str(&device_id) {
                    self.update_peer(id, |peer| {
                        if peer.status == PeerStatus::Discovered {
                            peer.status = PeerStatus::Offline;
                        }
                    });
                }
            }
            NetworkEvent::ConnectionReady(metadata) => self.on_connection_ready(metadata),
            NetworkEvent::Message {
                connection_id,
                device_id,
                message,
            } => {
                if let Ok(peer_id) = Uuid::parse_str(&device_id) {
                    let is_current = self
                        .pair_sessions
                        .read()
                        .get(&peer_id)
                        .is_some_and(|session| session.connection_id == connection_id);
                    if is_current {
                        self.on_message(peer_id, message);
                    }
                }
            }
            NetworkEvent::Disconnected {
                connection_id,
                device_id,
                reason,
            } => {
                if let Ok(peer_id) = Uuid::parse_str(&device_id) {
                    let is_current = self
                        .pair_sessions
                        .read()
                        .get(&peer_id)
                        .is_some_and(|session| session.connection_id == connection_id);
                    if is_current {
                        self.on_disconnected(peer_id, &reason);
                    }
                }
            }
            NetworkEvent::Error(error) => self.add_log(LogLevel::Warning, error),
        }
    }

    fn on_discovered(&self, record: crate::discovery::DiscoveryRecord) {
        let Ok(peer_id) = Uuid::parse_str(&record.device_id) else {
            return;
        };
        let address = record
            .addresses
            .first()
            .map(|address| format!("{address}:{}", record.port));
        let os = match record.platform.as_str() {
            "macos" => OsKind::Macos,
            "windows" => OsKind::Windows,
            _ => OsKind::Unknown,
        };
        let now = unix_millis();
        let mut snapshot = self.snapshot.write();
        if let Some(peer) = snapshot.peers.iter_mut().find(|peer| peer.id == peer_id) {
            peer.name = record.name;
            peer.os = os;
            peer.version = record.version;
            peer.address = address;
            peer.last_seen_at = now;
            if peer.status == PeerStatus::Offline {
                peer.status = PeerStatus::Discovered;
            }
        } else {
            snapshot.peers.push(PeerInfo {
                id: peer_id,
                name: record.name,
                os,
                version: record.version,
                status: PeerStatus::Discovered,
                address,
                latency_ms: None,
                fingerprint: None,
                pairing_code: None,
                last_seen_at: now,
                screens: Vec::new(),
            });
        }
        drop(snapshot);
        self.emit_snapshot();
    }

    fn on_connection_ready(&self, metadata: ConnectionMetadata) {
        let Ok(peer_id) = Uuid::parse_str(&metadata.device_id) else {
            if let Some(network) = self.network.lock().as_ref() {
                network.disconnect(&metadata.device_id, "invalid device UUID");
            }
            return;
        };
        let compatible = ["screens-v1", "layout-v1", "input-v1"]
            .iter()
            .all(|required| metadata.capabilities.iter().any(|value| value == required));
        if !compatible {
            self.update_peer(peer_id, |peer| peer.status = PeerStatus::Rejected);
            if let Some(network) = self.network.lock().as_ref() {
                network.disconnect(&metadata.device_id, "incompatible capabilities");
            }
            self.add_log(
                LogLevel::Warning,
                format!(
                    "已拒绝 {}：InputMesh {} 不支持本版本所需协议能力",
                    metadata.name, metadata.app_version
                ),
            );
            return;
        }
        let trusted = self.config.read().trusted_peer(peer_id).cloned();
        if trusted
            .as_ref()
            .is_some_and(|trusted| trusted.noise_static_public_key != metadata.remote_static_key)
        {
            self.update_peer(peer_id, |peer| peer.status = PeerStatus::Rejected);
            if let Some(network) = self.network.lock().as_ref() {
                network.disconnect(&metadata.device_id, "trusted peer public key changed");
            }
            self.add_log(
                LogLevel::Error,
                format!("已拒绝 {}：设备公钥与历史配对记录不一致", metadata.name),
            );
            return;
        }

        let request_id = metadata.connection_id.to_string();
        let local_approved = trusted.is_some();
        self.pair_sessions.write().insert(
            peer_id,
            PairSession {
                connection_id: metadata.connection_id,
                request_id: request_id.clone(),
                remote_request_id: None,
                remote_static_key: metadata.remote_static_key,
                local_approved,
                remote_approved: false,
            },
        );
        let os = match metadata.platform {
            Platform::Macos => OsKind::Macos,
            Platform::Windows => OsKind::Windows,
        };
        let now = unix_millis();
        let display_fingerprint = fingerprint(&metadata.remote_static_key);
        {
            let mut snapshot = self.snapshot.write();
            if let Some(peer) = snapshot.peers.iter_mut().find(|peer| peer.id == peer_id) {
                peer.name = metadata.name.clone();
                peer.os = os;
                peer.version = display_os_version(metadata.platform, &metadata.os_version);
                peer.status = PeerStatus::Pairing;
                peer.address = Some(metadata.address.to_string());
                peer.fingerprint = Some(display_fingerprint.clone());
                peer.pairing_code = Some(metadata.pairing_code.clone());
                peer.last_seen_at = now;
            } else {
                snapshot.peers.push(PeerInfo {
                    id: peer_id,
                    name: metadata.name.clone(),
                    os,
                    version: display_os_version(metadata.platform, &metadata.os_version),
                    status: PeerStatus::Pairing,
                    address: Some(metadata.address.to_string()),
                    latency_ms: None,
                    fingerprint: Some(display_fingerprint),
                    pairing_code: Some(metadata.pairing_code.clone()),
                    last_seen_at: now,
                    screens: Vec::new(),
                });
            }
        }
        let _ = self.send_to(
            peer_id,
            WireMessage::new(Message::PairRequest(PairRequest {
                request_id: request_id.clone(),
                device_id: self.snapshot.read().local_device.id.to_string(),
            })),
        );
        self.emit_snapshot();
    }

    fn on_message(&self, peer_id: DeviceId, message: WireMessage) {
        let allowed_while_pairing = matches!(
            &message.message,
            Message::PairRequest(_)
                | Message::PairApproval(_)
                | Message::PairReject(_)
                | Message::Error(_)
        );
        if !allowed_while_pairing && !self.peer_is_connected(peer_id) {
            return;
        }
        match message.message {
            Message::Screens(screens) => self.on_remote_screens(peer_id, screens),
            Message::Layout(layout) => self.on_remote_layout(peer_id, layout),
            Message::PairRequest(request) => self.on_pair_request(peer_id, request),
            Message::PairApproval(approval) => self.on_pair_approval(peer_id, approval),
            Message::PairReject(reject) => {
                let valid = self
                    .pair_sessions
                    .read()
                    .get(&peer_id)
                    .is_some_and(|session| session.request_id == reject.request_id);
                if !valid {
                    return;
                }
                self.update_peer(peer_id, |peer| {
                    peer.status = PeerStatus::Rejected;
                    peer.pairing_code = None;
                });
                self.add_log(
                    LogLevel::Warning,
                    reject.reason.unwrap_or_else(|| "远端拒绝配对".into()),
                );
                self.config.write().remove_trusted_peer(peer_id);
                if let Err(error) = self.persist_config() {
                    self.add_log(LogLevel::Error, format!("取消设备信任时保存失败：{error}"));
                }
                if let Some(network) = self.network.lock().as_ref() {
                    network.disconnect(&peer_id.to_string(), "remote revoked trust");
                }
            }
            Message::ControlClaim(claim) => self.on_control_claim(peer_id, claim),
            Message::ControlLease(lease) => self.on_control_lease(peer_id, lease),
            Message::Focus(focus) => self.on_remote_focus(peer_id, focus),
            Message::Input(input) => self.on_remote_input(peer_id, input),
            Message::Pong(pong) => {
                let latency = unix_millis()
                    .saturating_sub(pong.nonce)
                    .min(u64::from(u32::MAX));
                self.update_peer(peer_id, |peer| peer.latency_ms = Some(latency as u32));
            }
            Message::Error(error) => {
                self.add_log(LogLevel::Warning, format!("远端：{}", error.message));
            }
            Message::ControlRelease(release) => {
                if self.accepts_input(peer_id, &release.lease_id) {
                    self.release_remote_inputs();
                }
            }
            Message::Hello(_) | Message::Ping(_) => {}
        }
    }

    fn on_pair_request(&self, peer_id: DeviceId, request: PairRequest) {
        if request.device_id != peer_id.to_string() || request.request_id.len() > 128 {
            return;
        }
        let local_approved = {
            let mut sessions = self.pair_sessions.write();
            let Some(session) = sessions.get_mut(&peer_id) else {
                return;
            };
            if session
                .remote_request_id
                .as_ref()
                .is_some_and(|existing| existing != &request.request_id)
            {
                return;
            }
            session.remote_request_id = Some(request.request_id.clone());
            session.local_approved
        };
        if local_approved {
            let _ = self.send_pair_approval(peer_id, request.request_id);
        }
    }

    fn on_pair_approval(&self, peer_id: DeviceId, approval: PairApproval) {
        if approval.peer_id != peer_id.to_string() {
            return;
        }
        let accepted = {
            let mut sessions = self.pair_sessions.write();
            let Some(session) = sessions.get_mut(&peer_id) else {
                return;
            };
            if approval.request_id != session.request_id {
                false
            } else {
                session.remote_approved = true;
                true
            }
        };
        if accepted {
            self.refresh_peer_trust_status(peer_id);
        }
    }

    fn send_pair_approval(&self, peer_id: DeviceId, request_id: String) -> Result<(), String> {
        self.send_to(
            peer_id,
            WireMessage::new(Message::PairApproval(PairApproval {
                request_id,
                peer_id: self.snapshot.read().local_device.id.to_string(),
            })),
        )
    }

    fn on_remote_screens(&self, peer_id: DeviceId, screens: Screens) {
        let peer_name = self
            .snapshot
            .read()
            .peers
            .iter()
            .find(|peer| peer.id == peer_id)
            .map(|peer| peer.name.clone())
            .unwrap_or_else(|| "Remote computer".into());
        let placements = self.config.read().screen_layout.clone();
        let current_right = self
            .topology
            .read()
            .screens()
            .iter()
            .map(|screen| i64::from(screen.x) + i64::from(screen.width))
            .max()
            .unwrap_or(0)
            .saturating_add(80)
            .clamp(i64::from(i32::MIN), i64::from(i32::MAX)) as i32;
        let min_x = screens
            .screens
            .iter()
            .map(|screen| screen.origin_x)
            .min()
            .unwrap_or(0);
        let min_y = screens
            .screens
            .iter()
            .map(|screen| screen.origin_y)
            .min()
            .unwrap_or(0);
        let incoming_ids: HashSet<_> = screens
            .screens
            .iter()
            .map(|screen| screen.screen_id.as_str())
            .collect();

        let mut topology = self.topology.write();
        let stale: Vec<_> = topology
            .screens()
            .iter()
            .filter(|screen| {
                screen.owner_device_id == peer_id && !incoming_ids.contains(screen.id.as_str())
            })
            .map(|screen| screen.id.clone())
            .collect();
        for id in stale {
            topology.remove_screen(&id);
        }
        for descriptor in screens.screens {
            if descriptor.width_px == 0 || descriptor.height_px == 0 {
                continue;
            }
            let saved = placements.iter().find(|saved| {
                saved.screen_id == descriptor.screen_id && saved.owner_device_id == peer_id
            });
            let screen = ScreenInfo {
                id: descriptor.screen_id.clone(),
                native_id: descriptor.screen_id.clone(),
                owner_device_id: peer_id,
                owner_name: peer_name.clone(),
                name: descriptor.name,
                width: descriptor.width_px,
                height: descriptor.height_px,
                scale_factor: descriptor.scale_factor,
                x: saved
                    .map(|placement| placement.x)
                    .unwrap_or_else(|| current_right.saturating_add(descriptor.origin_x - min_x)),
                y: saved
                    .map(|placement| placement.y)
                    .unwrap_or(descriptor.origin_y - min_y),
                primary: descriptor.primary,
                enabled: saved
                    .map(|placement| placement.enabled)
                    .unwrap_or(descriptor.enabled),
                online: true,
            };
            let _ = topology.upsert_screen(screen);
        }
        let peer_screens: Vec<_> = topology
            .screens()
            .iter()
            .filter(|screen| screen.owner_device_id == peer_id)
            .cloned()
            .collect();
        let all_screens = topology.screens().to_vec();
        drop(topology);
        self.update_snapshot(|snapshot| {
            snapshot.screens = all_screens;
            if let Some(peer) = snapshot.peers.iter_mut().find(|peer| peer.id == peer_id) {
                peer.screens = peer_screens;
            }
        });
        // One deterministic endpoint republishes the complete canvas after the
        // screen inventory is known. This prevents both peers from retaining
        // different default placements after reconnecting.
        if self.snapshot.read().local_device.id.as_u128() > peer_id.as_u128() {
            self.broadcast_layout();
        }
    }

    fn on_remote_layout(&self, peer_id: DeviceId, layout: Layout) {
        if layout.source_device_id != peer_id.to_string() {
            return;
        }
        if self
            .remote_layout_revisions
            .read()
            .get(&peer_id)
            .is_some_and(|revision| layout.revision <= *revision)
        {
            return;
        }

        let mut seen = HashSet::with_capacity(layout.placements.len());
        let mut topology = self.topology.read().clone();
        for placement in &layout.placements {
            let Ok(owner_id) = Uuid::parse_str(&placement.owner_device_id) else {
                return;
            };
            if placement.screen_id.trim().is_empty() || !seen.insert(&placement.screen_id) {
                return;
            }
            let Some(existing) = topology.screen(&placement.screen_id) else {
                // Screen inventory is delivered before layouts on the same
                // authenticated TCP stream. A layout for an unknown screen is
                // stale or malformed, so apply none of it.
                return;
            };
            if existing.owner_device_id != owner_id {
                return;
            }
            if topology
                .set_screen_position(&placement.screen_id, placement.x, placement.y)
                .and_then(|()| topology.set_screen_enabled(&placement.screen_id, placement.enabled))
                .is_err()
            {
                return;
            }
        }

        let local_id = self.snapshot.read().local_device.id;
        if !topology
            .screens()
            .iter()
            .any(|screen| screen.owner_device_id == local_id && screen.is_available())
        {
            return;
        }
        if self.commit_topology(topology).is_ok() {
            self.remote_layout_revisions
                .write()
                .insert(peer_id, layout.revision);
        }
    }

    fn on_control_claim(&self, peer_id: DeviceId, claim: ControlClaim) {
        if !self.snapshot.read().sharing_enabled
            || !self.peer_is_connected(peer_id)
            || claim.controller_device_id != peer_id.to_string()
        {
            tracing::debug!(%peer_id, claim_id = %claim.claim_id, "rejected control claim before parsing");
            return;
        }
        let Some((generation, claimed_device_id)) = parse_claim(&claim.claim_id) else {
            return;
        };
        if claimed_device_id != peer_id.to_string()
            || !(1_000..=15_000).contains(&claim.requested_lease_ms)
            || claim.input_set_id.len() > 128
        {
            tracing::debug!(%peer_id, claim_id = %claim.claim_id, "rejected malformed control claim");
            return;
        }
        let local_id = self.snapshot.read().local_device.id;
        let mut control = self.control.lock();
        if control_claim_is_stale(&control, local_id, generation, &claim.claim_id) {
            tracing::debug!(
                %peer_id,
                claim_id = %claim.claim_id,
                current_lease_id = %control.lease_id,
                "ignored stale control claim"
            );
            return;
        }
        // Claim generations are wall-clock-seeded Lamport values. Comparing
        // them prevents delayed cross-direction claims from leaving the peers
        // with different controllers, while the next local input can always
        // advance past the newest value it has observed.
        control.generation = generation;
        control.holder = peer_id;
        control.lease_id = claim.claim_id.clone();
        control.input_set_id = claim.input_set_id.clone();
        control.sequence = 0;
        control.last_native_pointer = None;
        control.claim_announced = false;
        control.last_remote_sequence = 0;
        control.edge_attempt = None;
        control.pointer_parking = None;
        tracing::debug!(%peer_id, claim_id = %claim.claim_id, "accepted control claim");
        let releases = drain_remote_releases(&mut control);
        let lease_id = control.lease_id.clone();
        drop(control);
        self.inject_release_events(releases);
        self.update_snapshot(|snapshot| snapshot.active_controller_id = peer_id);
        let _ = self.send_to(
            peer_id,
            WireMessage::new(Message::ControlLease(ControlLease {
                claim_id: claim.claim_id,
                lease_id,
                holder_device_id: peer_id.to_string(),
                input_set_id: claim.input_set_id,
                ttl_ms: CONTROL_LEASE_MS,
            })),
        );
    }

    fn on_control_lease(&self, peer_id: DeviceId, lease: ControlLease) {
        let local_id = self.snapshot.read().local_device.id;
        if lease.holder_device_id != local_id.to_string() || !self.peer_is_connected(peer_id) {
            return;
        }
        let control = self.control.lock();
        let _valid_ack = control.holder == local_id
            && lease.claim_id == control.lease_id
            && lease.lease_id == control.lease_id
            && lease.input_set_id == control.input_set_id
            && (1_000..=15_000).contains(&lease.ttl_ms);
    }

    fn on_remote_focus(&self, peer_id: DeviceId, focus: Focus) {
        tracing::debug!(
            %peer_id,
            lease_id = %focus.lease_id,
            screen_id = %focus.screen_id,
            "received remote pointer focus"
        );
        if !self.snapshot.read().sharing_enabled {
            tracing::debug!(%peer_id, "rejected remote pointer focus while sharing is disabled");
            return;
        }
        if !self.accepts_input(peer_id, &focus.lease_id) {
            let control = self.control.lock();
            tracing::debug!(
                %peer_id,
                lease_id = %focus.lease_id,
                holder = %control.holder,
                current_lease_id = %control.lease_id,
                "rejected remote pointer focus without the active lease"
            );
            return;
        }
        let local_id = self.snapshot.read().local_device.id;
        let Some(screen) = self.topology.read().screen(&focus.screen_id).cloned() else {
            tracing::debug!(
                %peer_id,
                screen_id = %focus.screen_id,
                "rejected remote pointer focus for an unknown screen"
            );
            return;
        };
        if screen.owner_device_id != local_id || !screen.is_available() {
            tracing::debug!(
                %peer_id,
                screen_id = %screen.id,
                owner_device_id = %screen.owner_device_id,
                %local_id,
                available = screen.is_available(),
                "rejected remote pointer focus for a non-local or unavailable screen"
            );
            return;
        }
        self.control.lock().pointer = Some(PointerPosition::new(
            screen.id.clone(),
            focus.normalized_x * f64::from(screen.width.saturating_sub(1)),
            focus.normalized_y * f64::from(screen.height.saturating_sub(1)),
        ));
        tracing::debug!(%peer_id, screen_id = %screen.id, "accepted remote pointer focus");
        self.set_active_screen_if_changed(&screen.id);
        let _ = self.inject_pointer(&screen.id, focus.normalized_x, focus.normalized_y);
    }

    fn on_remote_input(&self, peer_id: DeviceId, input: Input) {
        if !self.snapshot.read().sharing_enabled
            || !self.accepts_input_sequence(peer_id, &input.lease_id, input.sequence)
        {
            return;
        }
        let native = match input.event {
            InputEvent::PointerMoveNormalized(pointer) => {
                if self
                    .topology
                    .read()
                    .screen(&pointer.screen_id)
                    .is_none_or(|screen| {
                        screen.owner_device_id != self.snapshot.read().local_device.id
                            || !screen.is_available()
                    })
                {
                    return;
                }
                self.control.lock().pointer =
                    self.topology
                        .read()
                        .screen(&pointer.screen_id)
                        .map(|screen| {
                            PointerPosition::new(
                                pointer.screen_id.clone(),
                                pointer.x * f64::from(screen.width.saturating_sub(1)),
                                pointer.y * f64::from(screen.height.saturating_sub(1)),
                            )
                        });
                tracing::trace!(
                    %peer_id,
                    screen_id = %pointer.screen_id,
                    x = pointer.x,
                    y = pointer.y,
                    "injecting remote pointer position"
                );
                let _ = self.inject_pointer(&pointer.screen_id, pointer.x, pointer.y);
                self.set_active_screen_if_changed(&pointer.screen_id);
                return;
            }
            InputEvent::PointerMoveRelative(_) => return,
            InputEvent::Button(button) => NativeInputEvent::PointerButton {
                button: match button.button {
                    PointerButton::Left => "Left",
                    PointerButton::Middle => "Middle",
                    PointerButton::Right => "Right",
                    PointerButton::Back | PointerButton::Forward => return,
                }
                .into(),
                pressed: button.state == ButtonState::Pressed,
            },
            InputEvent::Wheel(wheel) => NativeInputEvent::Wheel {
                delta_x: wheel.delta_x.round() as i64,
                delta_y: wheel.delta_y.round() as i64,
            },
            InputEvent::Key(key) => {
                let CanonicalKeyCode::Hid(code) = key.code else {
                    return;
                };
                if code.usage_page != 0x07 {
                    return;
                }
                let Some(name) = hid_to_key_name(code.usage) else {
                    return;
                };
                NativeInputEvent::Key {
                    code: name,
                    pressed: key.state == KeyState::Pressed,
                }
            }
        };
        self.track_remote_input(&native);
        if let NativeInputEvent::Key { code, pressed } = &native {
            tracing::debug!(%peer_id, %code, %pressed, "injecting remote key");
        }
        if let Err(error) = self.input.inject(native) {
            self.add_log(LogLevel::Warning, error);
        }
    }

    fn handle_local_input(&self, event: NativeInputEvent) -> bool {
        if !self.snapshot.read().sharing_enabled {
            return false;
        }
        let local_id = self.snapshot.read().local_device.id;
        let settings = self.snapshot.read().settings.clone();
        let pointer_can_reclaim = local_input_can_reclaim_control(&event, &settings);
        let takeover_pointer = self.local_pointer_for_input(&event, local_id);
        let (claim, releases, claimed_screen_id) = {
            let mut control = self.control.lock();
            if control.holder != local_id || !control.claim_announced {
                let taking_over = control.holder != local_id;
                if taking_over && !pointer_can_reclaim {
                    return false;
                }
                control.generation = next_claim_generation(control.generation);
                control.holder = local_id;
                control.lease_id = format!("{:020}:{local_id}", control.generation);
                control.input_set_id = format!("physical:{local_id}");
                control.sequence = 0;
                control.last_native_pointer = None;
                control.claim_announced = true;
                control.last_remote_sequence = 0;
                control.edge_attempt = None;
                control.pointer_parking = None;
                if taking_over {
                    control.pointer.clone_from(&takeover_pointer);
                }
                let claim = ControlClaim {
                    claim_id: control.lease_id.clone(),
                    controller_device_id: local_id.to_string(),
                    input_set_id: control.input_set_id.clone(),
                    requested_lease_ms: CONTROL_LEASE_MS,
                };
                let claimed_screen_id = control
                    .pointer
                    .as_ref()
                    .map(|pointer| pointer.screen_id.clone());
                (
                    Some(claim),
                    drain_remote_releases(&mut control),
                    claimed_screen_id,
                )
            } else {
                (None, Vec::new(), None)
            }
        };
        self.inject_release_events(releases);
        if let Some(claim) = claim {
            self.broadcast(WireMessage::new(Message::ControlClaim(claim)));
            self.update_snapshot(|snapshot| snapshot.active_controller_id = local_id);
            if let Some(screen_id) = claimed_screen_id {
                tracing::debug!(%screen_id, "local pointer reclaimed control");
                self.set_active_screen_if_changed(&screen_id);
            }
        }

        let mut control = self.control.lock();

        match event {
            NativeInputEvent::PointerMoved {
                x,
                y,
                delta_x: native_delta_x,
                delta_y: native_delta_y,
            } => {
                let mut previous_native = control.last_native_pointer.replace((x, y));
                let local_hit = self.native_screen_at(x, y);

                if let Some((screen_id, bounds)) = local_hit.as_ref()
                    && control.pointer.as_ref().is_none_or(|pointer| {
                        self.screen_owner(&pointer.screen_id) == Some(local_id)
                    })
                {
                    // Anchor topology movement at the previous native cursor
                    // position. Anchoring at the current position and then
                    // adding this event's delta applies every motion twice.
                    if let Some((previous_x, previous_y)) = previous_native {
                        if let Some((previous_screen_id, previous_bounds)) =
                            self.native_screen_at(previous_x, previous_y)
                        {
                            let local_x = (previous_x - f64::from(previous_bounds.x))
                                .clamp(0.0, f64::from(previous_bounds.width.saturating_sub(1)));
                            let local_y = (previous_y - f64::from(previous_bounds.y))
                                .clamp(0.0, f64::from(previous_bounds.height.saturating_sub(1)));
                            control.pointer =
                                Some(PointerPosition::new(previous_screen_id, local_x, local_y));
                        }
                    } else {
                        let local_x = (x - f64::from(bounds.x))
                            .clamp(0.0, f64::from(bounds.width.saturating_sub(1)));
                        let local_y = (y - f64::from(bounds.y))
                            .clamp(0.0, f64::from(bounds.height.saturating_sub(1)));
                        control.pointer =
                            Some(PointerPosition::new(screen_id.clone(), local_x, local_y));
                        previous_native = Some((x, y));
                    }
                }

                let Some(mut start) = control.pointer.clone() else {
                    return false;
                };
                let start_owner = self.screen_owner(&start.screen_id);
                if start_owner == Some(local_id) && control.pointer_parking.take().is_some() {
                    // The pointer has just returned from the parking position to
                    // a local screen. Do not interpret that warp as user motion.
                    previous_native = Some((x, y));
                }
                let hardware_delta = native_delta_x.zip(native_delta_y);
                let (mut delta_x, mut delta_y) = if start_owner != Some(local_id) {
                    if let Some(delta) = hardware_delta {
                        delta
                    } else if let Some((parking_x, parking_y)) = control.pointer_parking {
                        // While remote input is active, suppressed absolute mouse
                        // events are measured from a stable local parking point.
                        // This recovers usable relative motion with rdev on both OSes.
                        control.last_native_pointer = Some((parking_x, parking_y));
                        (x - parking_x, y - parking_y)
                    } else {
                        previous_native
                            .map(|(previous_x, previous_y)| (x - previous_x, y - previous_y))
                            .unwrap_or((0.0, 0.0))
                    }
                } else {
                    previous_native
                        .map(|(previous_x, previous_y)| (x - previous_x, y - previous_y))
                        .unwrap_or((0.0, 0.0))
                };
                if start_owner == Some(local_id) {
                    if let Some(bounds) = self.native_screens.read().get(&start.screen_id) {
                        let boundary_delta_x = hardware_delta
                            .map(|delta| delta.0)
                            .filter(|delta| *delta != 0.0)
                            .unwrap_or(delta_x);
                        let boundary_delta_y = hardware_delta
                            .map(|delta| delta.1)
                            .filter(|delta| *delta != 0.0)
                            .unwrap_or(delta_y);
                        if let Some(adjusted) =
                            native_edge_overshoot(x, bounds.x, bounds.width, boundary_delta_x)
                        {
                            delta_x = adjusted;
                        }
                        if let Some(adjusted) =
                            native_edge_overshoot(y, bounds.y, bounds.height, boundary_delta_y)
                        {
                            delta_y = adjusted;
                        }
                    }
                    // WH_MOUSE_LL exposes only the cursor's clamped absolute
                    // position. Once a physical Windows mouse is already on a
                    // display's final pixel, continued outward travel arrives
                    // as another WM_MOUSEMOVE with a (0, 0) delta. Recover that
                    // intent only when the exact native edge has a remote
                    // topology neighbour at the same edge fraction.
                    if cfg!(target_os = "windows")
                        && hardware_delta == Some((0.0, 0.0))
                        && let Some((native_screen_id, native_bounds)) = local_hit.as_ref()
                    {
                        let edge_start = PointerPosition::new(
                            native_screen_id.clone(),
                            (x - f64::from(native_bounds.x))
                                .clamp(0.0, f64::from(native_bounds.width.saturating_sub(1))),
                            (y - f64::from(native_bounds.y))
                                .clamp(0.0, f64::from(native_bounds.height.saturating_sub(1))),
                        );
                        if let Some((fallback_x, fallback_y)) = clamped_remote_edge_delta(
                            &self.topology.read(),
                            &edge_start,
                            *native_bounds,
                            x,
                            y,
                            local_id,
                        ) {
                            start = edge_start;
                            delta_x = fallback_x;
                            delta_y = fallback_y;
                        }
                    }
                }
                let moved = match self.topology.read().move_pointer_by(
                    &start.screen_id,
                    start.x,
                    start.y,
                    delta_x,
                    delta_y,
                ) {
                    Ok(moved) => moved,
                    Err(_) => return false,
                };
                let previous_screen = start.screen_id.clone();
                let target = moved.position.clone();
                let target_owner = self.screen_owner(&target.screen_id);
                if previous_screen != target.screen_id {
                    tracing::debug!(
                        from = %previous_screen,
                        to = %target.screen_id,
                        ?target_owner,
                        %local_id,
                        delta_x,
                        delta_y,
                        "pointer crossed a topology edge"
                    );
                }
                let cross_device_transition = moved.transitions.iter().find(|transition| {
                    self.screen_owner(&transition.from_screen_id) == Some(local_id)
                        && self.screen_owner(&transition.to_screen_id) != Some(local_id)
                });
                if let Some(transition) = cross_device_transition {
                    let settings = self.snapshot.read().settings.clone();
                    let travel = match transition.direction {
                        Direction::Left | Direction::Right => delta_x.abs(),
                        Direction::Up | Direction::Down => delta_y.abs(),
                    };
                    if !edge_transition_ready(
                        &mut control.edge_attempt,
                        transition,
                        travel,
                        &settings,
                    ) {
                        control.pointer = Some(start);
                        return false;
                    }
                } else if moved.transitions.is_empty() {
                    control.edge_attempt = None;
                }

                let previous_owner = start_owner;
                control.pointer = Some(target.clone());
                let lease_id = control.lease_id.clone();
                let input_set_id = control.input_set_id.clone();
                let sequence = control.next_sequence();
                // Windows needs a stable native parking point because its
                // low-level hook reports clamped desktop coordinates. macOS
                // supplies genuine hardware deltas while the event is
                // suppressed, so parking there only creates a needless warp
                // and can produce an untagged follow-up mouse event.
                let parking = if cfg!(target_os = "windows")
                    && previous_owner == Some(local_id)
                    && target_owner.is_some_and(|owner| owner != local_id)
                {
                    self.native_screens
                        .read()
                        .get(&previous_screen)
                        .map(|bounds| {
                            (
                                f64::from(bounds.x) + f64::from(bounds.width) / 2.0,
                                f64::from(bounds.y) + f64::from(bounds.height) / 2.0,
                            )
                        })
                } else {
                    None
                };
                if let Some(parking) = parking {
                    control.pointer_parking = Some(parking);
                    control.last_native_pointer = Some(parking);
                }
                drop(control);

                self.set_active_screen_if_changed(&target.screen_id);
                if let Some((parking_x, parking_y)) = parking {
                    // SendInput invokes the Windows low-level hook
                    // synchronously. Calling it from inside the hook callback
                    // would re-enter rdev while its callback mutex is held and
                    // deadlock before the focus messages are sent. Defer the
                    // one-time parking warp until this callback has returned.
                    let input = Arc::clone(&self.input);
                    std::thread::spawn(move || {
                        let _ = input.inject(NativeInputEvent::PointerMoved {
                            x: parking_x,
                            y: parking_y,
                            delta_x: None,
                            delta_y: None,
                        });
                    });
                }
                if previous_screen != target.screen_id
                    && previous_owner.is_some_and(|owner| owner != local_id)
                {
                    let _ = self.send_to(
                        previous_owner.expect("checked above"),
                        WireMessage::new(Message::ControlRelease(
                            crate::protocol::ControlRelease {
                                lease_id: lease_id.clone(),
                            },
                        )),
                    );
                }
                if target_owner == Some(local_id) {
                    if previous_screen != target.screen_id && previous_owner != Some(local_id) {
                        let screen = self.topology.read().screen(&target.screen_id).cloned();
                        if let Some(screen) = screen {
                            let normalized_x =
                                target.x / f64::from(screen.width.saturating_sub(1).max(1));
                            let normalized_y =
                                target.y / f64::from(screen.height.saturating_sub(1).max(1));
                            let _ =
                                self.inject_pointer(&target.screen_id, normalized_x, normalized_y);
                        }
                        return true;
                    }
                    false
                } else if let Some(owner) = target_owner {
                    let Some(screen) = self.topology.read().screen(&target.screen_id).cloned()
                    else {
                        return false;
                    };
                    let normalized_x = (target.x
                        / f64::from(screen.width.saturating_sub(1).max(1)))
                    .clamp(0.0, 1.0);
                    let normalized_y = (target.y
                        / f64::from(screen.height.saturating_sub(1).max(1)))
                    .clamp(0.0, 1.0);
                    if previous_screen != target.screen_id {
                        let claim_result = self.send_to(
                            owner,
                            WireMessage::new(Message::ControlClaim(ControlClaim {
                                claim_id: lease_id.clone(),
                                controller_device_id: local_id.to_string(),
                                input_set_id: input_set_id.clone(),
                                requested_lease_ms: CONTROL_LEASE_MS,
                            })),
                        );
                        let focus_result = self.send_to(
                            owner,
                            WireMessage::new(Message::Focus(Focus {
                                lease_id: lease_id.clone(),
                                screen_id: target.screen_id.clone(),
                                normalized_x,
                                normalized_y,
                            })),
                        );
                        tracing::debug!(
                            %owner,
                            screen_id = %target.screen_id,
                            claim_sent = claim_result.is_ok(),
                            focus_sent = focus_result.is_ok(),
                            claim_error = ?claim_result.err(),
                            focus_error = ?focus_result.err(),
                            "sent remote pointer focus transition"
                        );
                    }
                    if self
                        .send_to(
                            owner,
                            WireMessage::new(Message::Input(Input {
                                lease_id,
                                sequence,
                                event: InputEvent::PointerMoveNormalized(PointerMoveNormalized {
                                    screen_id: target.screen_id,
                                    x: normalized_x,
                                    y: normalized_y,
                                }),
                            })),
                        )
                        .is_err()
                    {
                        self.reset_control_to_local();
                        false
                    } else {
                        true
                    }
                } else {
                    false
                }
            }
            other => {
                let Some(pointer) = control.pointer.as_ref() else {
                    return false;
                };
                let Some(owner) = self.screen_owner(&pointer.screen_id) else {
                    return false;
                };
                if owner == local_id {
                    update_pressed_keys_for_wire(&other, &mut control.pressed_hid);
                    return false;
                }
                let Some(input_event) = native_to_wire(other, &mut control.pressed_hid) else {
                    return false;
                };
                let message = WireMessage::new(Message::Input(Input {
                    lease_id: control.lease_id.clone(),
                    sequence: control.next_sequence(),
                    event: input_event,
                }));
                drop(control);
                if self.send_to(owner, message).is_err() {
                    self.reset_control_to_local();
                    false
                } else {
                    true
                }
            }
        }
    }

    fn accepts_input(&self, peer_id: DeviceId, lease_id: &str) -> bool {
        if !self.peer_is_connected(peer_id) {
            return false;
        }
        let control = self.control.lock();
        control.holder == peer_id && control.lease_id == lease_id
    }

    fn accepts_input_sequence(&self, peer_id: DeviceId, lease_id: &str, sequence: u64) -> bool {
        if !self.peer_is_connected(peer_id) {
            return false;
        }
        let mut control = self.control.lock();
        if control.holder != peer_id
            || control.lease_id != lease_id
            || sequence <= control.last_remote_sequence
        {
            return false;
        }
        control.last_remote_sequence = sequence;
        true
    }

    fn track_remote_input(&self, event: &NativeInputEvent) {
        let mut control = self.control.lock();
        match event {
            NativeInputEvent::Key { code, pressed } => {
                if *pressed {
                    control.remote_pressed_keys.insert(code.clone());
                } else {
                    control.remote_pressed_keys.remove(code);
                }
            }
            NativeInputEvent::PointerButton { button, pressed } => {
                if *pressed {
                    control.remote_pressed_buttons.insert(button.clone());
                } else {
                    control.remote_pressed_buttons.remove(button);
                }
            }
            NativeInputEvent::PointerMoved { .. } | NativeInputEvent::Wheel { .. } => {}
        }
    }

    fn release_remote_inputs(&self) {
        let releases = drain_remote_releases(&mut self.control.lock());
        self.inject_release_events(releases);
    }

    fn inject_release_events(&self, releases: Vec<NativeInputEvent>) {
        for event in releases {
            if let Err(error) = self.input.inject(event) {
                tracing::warn!(%error, "could not release remotely held input");
            }
        }
    }

    fn reset_control_to_local(&self) {
        let local_id = self.snapshot.read().local_device.id;
        let pointer = self
            .topology
            .read()
            .screens()
            .iter()
            .filter(|screen| screen.owner_device_id == local_id && screen.is_available())
            .min_by_key(|screen| !screen.primary)
            .map(|screen| {
                PointerPosition::new(
                    screen.id.clone(),
                    f64::from(screen.width) / 2.0,
                    f64::from(screen.height) / 2.0,
                )
            });
        let mut control = self.control.lock();
        control.generation = next_claim_generation(control.generation);
        control.holder = local_id;
        control.lease_id = format!("{:020}:{local_id}", control.generation);
        control.input_set_id = format!("physical:{local_id}");
        control.sequence = 0;
        control.pointer = pointer;
        control.last_native_pointer = None;
        control.pressed_hid.clear();
        control.claim_announced = false;
        control.last_remote_sequence = 0;
        control.edge_attempt = None;
        control.pointer_parking = None;
        let releases = drain_remote_releases(&mut control);
        let active_screen_id = control
            .pointer
            .as_ref()
            .map(|pointer| pointer.screen_id.clone());
        drop(control);
        self.inject_release_events(releases);
        self.input.set_cursor_hidden(false);
        self.update_snapshot(|snapshot| {
            snapshot.active_controller_id = local_id;
            snapshot.active_screen_id = active_screen_id;
        });
    }

    fn on_emergency_release(&self) {
        let lease_id = self.control.lock().lease_id.clone();
        self.broadcast(WireMessage::new(Message::ControlRelease(
            crate::protocol::ControlRelease { lease_id },
        )));
        self.reset_control_to_local();
        self.config.write().sharing_enabled = false;
        self.update_snapshot(|snapshot| snapshot.sharing_enabled = false);
        self.add_log(LogLevel::Warning, "已通过 Ctrl + Alt + Esc 紧急释放键鼠");
    }

    fn inject_pointer(
        &self,
        screen_id: &str,
        normalized_x: f64,
        normalized_y: f64,
    ) -> Result<(), String> {
        let bounds = *self
            .native_screens
            .read()
            .get(screen_id)
            .ok_or_else(|| format!("unknown native screen {screen_id}"))?;
        let x = f64::from(bounds.x)
            + normalized_x.clamp(0.0, 1.0) * f64::from(bounds.width.saturating_sub(1));
        let y = f64::from(bounds.y)
            + normalized_y.clamp(0.0, 1.0) * f64::from(bounds.height.saturating_sub(1));
        self.input.inject(NativeInputEvent::PointerMoved {
            x,
            y,
            delta_x: None,
            delta_y: None,
        })
    }

    fn native_screen_at(&self, x: f64, y: f64) -> Option<(String, NativeScreenBounds)> {
        self.native_screens
            .read()
            .iter()
            .find(|(_, bounds)| bounds.contains(x, y))
            .map(|(id, bounds)| (id.clone(), *bounds))
    }

    fn local_pointer_for_input(
        &self,
        event: &NativeInputEvent,
        local_id: DeviceId,
    ) -> Option<PointerPosition> {
        if let NativeInputEvent::PointerMoved { x, y, .. } = event
            && let Some((screen_id, bounds)) = self.native_screen_at(*x, *y)
            && self.screen_owner(&screen_id) == Some(local_id)
        {
            return Some(PointerPosition::new(
                screen_id,
                (*x - f64::from(bounds.x)).clamp(0.0, f64::from(bounds.width.saturating_sub(1))),
                (*y - f64::from(bounds.y)).clamp(0.0, f64::from(bounds.height.saturating_sub(1))),
            ));
        }
        self.topology
            .read()
            .screens()
            .iter()
            .filter(|screen| screen.owner_device_id == local_id && screen.is_available())
            .min_by_key(|screen| !screen.primary)
            .map(|screen| {
                PointerPosition::new(
                    screen.id.clone(),
                    f64::from(screen.width) / 2.0,
                    f64::from(screen.height) / 2.0,
                )
            })
    }

    fn screen_owner(&self, screen_id: &str) -> Option<DeviceId> {
        self.topology
            .read()
            .screen(screen_id)
            .map(|screen| screen.owner_device_id)
    }

    fn peer_is_connected(&self, peer_id: DeviceId) -> bool {
        self.snapshot
            .read()
            .peers
            .iter()
            .any(|peer| peer.id == peer_id && peer.status == PeerStatus::Connected)
    }

    fn refresh_peer_trust_status(&self, peer_id: DeviceId) {
        let session = self.pair_sessions.read().get(&peer_id).cloned();
        let connected = session
            .as_ref()
            .is_some_and(|session| session.local_approved && session.remote_approved);
        self.update_peer(peer_id, |peer| {
            peer.status = if connected {
                PeerStatus::Connected
            } else {
                PeerStatus::Pairing
            };
            if connected {
                peer.pairing_code = None;
            }
        });
        if connected {
            let name = self
                .snapshot
                .read()
                .peers
                .iter()
                .find(|peer| peer.id == peer_id)
                .map(|peer| peer.name.clone())
                .unwrap_or_else(|| peer_id.to_string());
            self.add_log(LogLevel::Info, format!("已与 {name} 建立可信加密连接"));
            let _ = self.send_to(peer_id, self.local_screens_message());
            self.send_announced_claim_to(peer_id);
        }
    }

    fn send_announced_claim_to(&self, peer_id: DeviceId) {
        let local_id = self.snapshot.read().local_device.id;
        let claim = {
            let control = self.control.lock();
            if control.holder != local_id || !control.claim_announced {
                return;
            }
            ControlClaim {
                claim_id: control.lease_id.clone(),
                controller_device_id: local_id.to_string(),
                input_set_id: control.input_set_id.clone(),
                requested_lease_ms: CONTROL_LEASE_MS,
            }
        };
        let _ = self.send_to(peer_id, WireMessage::new(Message::ControlClaim(claim)));
    }

    fn on_disconnected(&self, peer_id: DeviceId, reason: &str) {
        self.pair_sessions.write().remove(&peer_id);
        {
            let mut topology = self.topology.write();
            let remote_ids: Vec<_> = topology
                .screens()
                .iter()
                .filter(|screen| screen.owner_device_id == peer_id)
                .map(|screen| screen.id.clone())
                .collect();
            for id in remote_ids {
                if let Some(mut screen) = topology.remove_screen(&id) {
                    screen.online = false;
                    let _ = topology.upsert_screen(screen);
                }
            }
            let screens = topology.screens().to_vec();
            drop(topology);
            self.update_snapshot(|snapshot| snapshot.screens = screens);
        }
        self.update_peer(peer_id, |peer| {
            peer.status = PeerStatus::Offline;
            peer.pairing_code = None;
            for screen in &mut peer.screens {
                screen.online = false;
            }
        });

        let (holder, pointer_screen) = {
            let control = self.control.lock();
            (
                control.holder,
                control
                    .pointer
                    .as_ref()
                    .map(|pointer| pointer.screen_id.clone()),
            )
        };
        let focused_remote = pointer_screen
            .as_deref()
            .is_some_and(|screen_id| self.screen_owner(screen_id) == Some(peer_id));
        if holder == peer_id || focused_remote {
            self.reset_control_to_local();
        }
        self.add_log(LogLevel::Warning, format!("设备连接已断开：{reason}"));
    }

    fn local_screens_message(&self) -> WireMessage {
        let local_id = self.snapshot.read().local_device.id;
        let native = self.native_screens.read();
        let screens = self
            .topology
            .read()
            .screens()
            .iter()
            .filter(|screen| screen.owner_device_id == local_id)
            .map(|screen| {
                let bounds = native.get(&screen.id);
                ScreenDescriptor {
                    screen_id: screen.id.clone(),
                    name: screen.name.clone(),
                    origin_x: bounds.map_or(screen.x, |bounds| bounds.x),
                    origin_y: bounds.map_or(screen.y, |bounds| bounds.y),
                    width_px: screen.width,
                    height_px: screen.height,
                    scale_factor: screen.scale_factor,
                    primary: screen.primary,
                    enabled: screen.enabled,
                }
            })
            .collect();
        WireMessage::new(Message::Screens(Screens {
            revision: unix_millis(),
            screens,
        }))
    }

    fn broadcast_layout(&self) {
        let local_id = self.snapshot.read().local_device.id;
        let revision = self.layout_revision.fetch_add(1, Ordering::AcqRel) + 1;
        let placements = self
            .topology
            .read()
            .placements()
            .into_iter()
            .map(|placement| LayoutPlacement {
                screen_id: placement.screen_id,
                owner_device_id: placement.owner_device_id.to_string(),
                x: placement.x,
                y: placement.y,
                enabled: placement.enabled,
            })
            .collect();
        self.broadcast(WireMessage::new(Message::Layout(Layout {
            revision,
            source_device_id: local_id.to_string(),
            placements,
        })));
    }

    fn send_to(&self, peer_id: DeviceId, message: WireMessage) -> Result<(), String> {
        self.network
            .lock()
            .as_ref()
            .ok_or_else(|| "局域网服务尚未启动".to_string())?
            .send(&peer_id.to_string(), message)
    }

    fn broadcast(&self, message: WireMessage) {
        if let Some(network) = self.network.lock().as_ref() {
            network.broadcast(message);
        }
    }

    fn update_peer(&self, peer_id: DeviceId, update: impl FnOnce(&mut PeerInfo)) {
        let mut snapshot = self.snapshot.write();
        if let Some(peer) = snapshot.peers.iter_mut().find(|peer| peer.id == peer_id) {
            update(peer);
        }
        drop(snapshot);
        self.emit_snapshot();
    }

    fn commit_topology(&self, topology: ScreenTopology) -> Result<(), String> {
        let screens = topology.screens().to_vec();
        let current_placements = topology.placements();
        let mut next_config = self.config.read().clone();
        next_config.screen_layout.retain(|saved| {
            !current_placements.iter().any(|current| {
                current.screen_id == saved.screen_id
                    && current.owner_device_id == saved.owner_device_id
            })
        });
        next_config.screen_layout.extend(current_placements);
        next_config
            .save_atomic(&self.config_path)
            .map_err(|error| error.to_string())?;

        *self.config.write() = next_config;
        *self.topology.write() = topology;
        let local_id = self.snapshot.read().local_device.id;
        let active_screen_id = {
            let mut control = self.control.lock();
            let pointer_is_available = control.pointer.as_ref().is_some_and(|pointer| {
                screens
                    .iter()
                    .any(|screen| screen.id == pointer.screen_id && screen.is_available())
            });
            if !pointer_is_available {
                control.pointer = screens
                    .iter()
                    .filter(|screen| screen.owner_device_id == local_id && screen.is_available())
                    .min_by_key(|screen| !screen.primary)
                    .map(|screen| {
                        PointerPosition::new(
                            screen.id.clone(),
                            f64::from(screen.width) / 2.0,
                            f64::from(screen.height) / 2.0,
                        )
                    });
                control.edge_attempt = None;
                control.pointer_parking = None;
            }
            control
                .pointer
                .as_ref()
                .map(|pointer| pointer.screen_id.clone())
        };
        self.update_snapshot(|snapshot| {
            snapshot.screens.clone_from(&screens);
            snapshot.active_screen_id = active_screen_id;
            for peer in &mut snapshot.peers {
                peer.screens = screens
                    .iter()
                    .filter(|screen| screen.owner_device_id == peer.id)
                    .cloned()
                    .collect();
            }
        });
        Ok(())
    }

    fn persist_config(&self) -> Result<(), String> {
        self.config
            .read()
            .save_atomic(&self.config_path)
            .map_err(|error| error.to_string())
    }

    fn add_log(&self, level: LogLevel, message: impl Into<String>) {
        let message = message.into();
        {
            let mut snapshot = self.snapshot.write();
            snapshot.logs.insert(
                0,
                ActivityLog {
                    id: Uuid::new_v4().to_string(),
                    timestamp: unix_millis(),
                    level,
                    message,
                },
            );
            snapshot.logs.truncate(MAX_LOG_ENTRIES);
        }
        self.emit_snapshot();
    }

    fn update_snapshot(&self, update: impl FnOnce(&mut AppSnapshot)) {
        update(&mut self.snapshot.write());
        self.emit_snapshot();
    }

    fn set_active_screen_if_changed(&self, screen_id: &str) {
        let local_id = self.snapshot.read().local_device.id;
        let cursor_should_hide = self
            .topology
            .read()
            .screen(screen_id)
            .is_some_and(|screen| screen.owner_device_id != local_id);
        #[cfg(target_os = "macos")]
        {
            let input = Arc::clone(&self.input);
            if let Err(error) = self
                .app
                .run_on_main_thread(move || input.set_cursor_hidden(cursor_should_hide))
            {
                tracing::warn!(%error, "could not schedule local cursor visibility update");
            }
        }
        #[cfg(not(target_os = "macos"))]
        self.input.set_cursor_hidden(cursor_should_hide);
        let changed = {
            let mut snapshot = self.snapshot.write();
            if snapshot.active_screen_id.as_deref() == Some(screen_id) {
                false
            } else {
                snapshot.active_screen_id = Some(screen_id.to_string());
                true
            }
        };
        if changed {
            self.emit_snapshot();
        }
    }

    fn emit_snapshot(&self) {
        let _ = self.app.emit(SNAPSHOT_EVENT, self.snapshot.read().clone());
    }
}

pub fn setup(app: &mut tauri::App) -> Result<(), Box<dyn std::error::Error>> {
    let core = AppCore::load(app.handle().clone())?;
    let resume_sharing = core.config.read().sharing_enabled;
    app.manage(core.clone());
    if resume_sharing {
        if let Err(error) = core.set_sharing_enabled(true) {
            core.add_log(
                LogLevel::Warning,
                format!("无法恢复上次的键鼠共享状态：{error}"),
            );
            tracing::warn!(%error, "could not resume persisted input sharing");
        } else {
            tracing::info!("resumed persisted input sharing");
        }
    }
    tauri::async_runtime::spawn(async move {
        let _ = core.start_network().await;
    });
    Ok(())
}

fn enumerate_local_screens(
    device: &DeviceInfo,
) -> Result<(ScreenTopology, HashMap<String, NativeScreenBounds>), String> {
    let displays = DisplayInfo::all().map_err(|error| error.to_string())?;
    if displays.is_empty() {
        return Err("系统未报告任何显示器".into());
    }
    let mut native = HashMap::new();
    let screens: Vec<_> = displays
        .into_iter()
        .map(|display| {
            let native_id = stable_display_native_id(&display);
            let id = format!("{}:{native_id}", device.id);
            native.insert(
                id.clone(),
                NativeScreenBounds {
                    x: display.x,
                    y: display.y,
                    width: display.width,
                    height: display.height,
                },
            );
            ScreenInfo {
                id,
                native_id: display.id.to_string(),
                owner_device_id: device.id,
                owner_name: device.name.clone(),
                name: if display.friendly_name.trim().is_empty() {
                    display.name
                } else {
                    display.friendly_name
                },
                width: display.width,
                height: display.height,
                scale_factor: f64::from(display.scale_factor),
                x: display.x,
                y: display.y,
                primary: display.is_primary,
                enabled: true,
                online: true,
            }
        })
        .collect();
    let topology = ScreenTopology::new(screens).map_err(|error| error.to_string())?;
    Ok((topology, native))
}

fn stable_display_native_id(display: &DisplayInfo) -> String {
    #[cfg(target_os = "windows")]
    {
        let identity = format!(
            "{}|{}|{}x{}",
            display.name, display.friendly_name, display.width_mm, display.height_mm
        );
        let digest = Sha256::digest(identity.as_bytes());
        let suffix = digest[..8]
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
        format!("win-{suffix}")
    }
    #[cfg(not(target_os = "windows"))]
    {
        display.id.to_string()
    }
}

fn migrate_legacy_windows_placements(config: &mut AppConfig, topology: &ScreenTopology) -> bool {
    #[cfg(target_os = "windows")]
    {
        let mut migrated = Vec::new();
        for screen in topology.screens() {
            if config
                .screen_layout
                .iter()
                .any(|placement| placement.screen_id == screen.id)
            {
                continue;
            }
            let legacy_id = format!("{}:{}", screen.owner_device_id, screen.native_id);
            if let Some(saved) = config.screen_layout.iter().find(|placement| {
                placement.owner_device_id == screen.owner_device_id
                    && placement.screen_id == legacy_id
            }) {
                let mut saved = saved.clone();
                saved.screen_id = screen.id.clone();
                migrated.push(saved);
            }
        }
        let changed = !migrated.is_empty();
        config.screen_layout.extend(migrated);
        changed
    }
    #[cfg(not(target_os = "windows"))]
    {
        let _ = (config, topology);
        false
    }
}

fn permission_state(permission: PlatformPermission) -> PermissionState {
    PermissionState {
        accessibility: permission.accessibility,
        input_monitoring: permission.input_monitoring,
        requires_action: permission.requires_action,
        help_text: permission.help_text,
    }
}

fn display_os_version(platform: Platform, version: &str) -> String {
    if !version.trim().is_empty() {
        return version.to_string();
    }
    match platform {
        Platform::Macos => "macOS".into(),
        Platform::Windows => "Windows".into(),
    }
}

fn edge_transition_ready(
    attempt: &mut Option<EdgeAttempt>,
    transition: &ScreenTransition,
    travel_px: f64,
    settings: &SharingSettings,
) -> bool {
    let now = Instant::now();
    let matches_existing = attempt.as_ref().is_some_and(|current| {
        current.from_screen_id == transition.from_screen_id
            && current.to_screen_id == transition.to_screen_id
            && current.direction == transition.direction
    });
    if !matches_existing {
        *attempt = Some(EdgeAttempt {
            from_screen_id: transition.from_screen_id.clone(),
            to_screen_id: transition.to_screen_id.clone(),
            direction: transition.direction,
            started_at: now,
            travel_px: 0.0,
        });
    }
    let current = attempt.as_mut().expect("edge attempt was just initialized");
    current.travel_px += travel_px.max(0.0);
    let delay_ready =
        current.started_at.elapsed().as_millis() >= u128::from(settings.switch_delay_ms);
    let resistance_ready = current.travel_px >= f64::from(settings.edge_resistance_px);
    if delay_ready && resistance_ready {
        *attempt = None;
        true
    } else {
        false
    }
}

fn local_input_can_reclaim_control(event: &NativeInputEvent, settings: &SharingSettings) -> bool {
    settings.take_control_on_local_input || matches!(event, NativeInputEvent::PointerMoved { .. })
}

/// Native cursors are clamped to the last pixel of a display. Reaching that
/// pixel with a slow 1 px movement would otherwise leave the logical pointer
/// one pixel short of the topology boundary, after which Windows reports only
/// zero coordinate deltas. Add the smallest possible outward overshoot while
/// preserving the device's original movement magnitude.
fn native_edge_overshoot(
    native_position: f64,
    native_origin: i32,
    native_extent: u32,
    delta: f64,
) -> Option<f64> {
    if native_extent == 0 || !native_position.is_finite() || !delta.is_finite() {
        return None;
    }
    let first = f64::from(native_origin);
    let last = first + f64::from(native_extent.saturating_sub(1));
    if native_position >= last && delta > 0.0 {
        Some(delta.max(1.0) + 1.0)
    } else if native_position <= first && delta < 0.0 {
        Some(delta.min(-1.0) - 1.0)
    } else {
        None
    }
}

/// Recovers outward physical motion that Windows reports at an unchanged,
/// display-clamped cursor position. Candidates are limited to native edges
/// whose matching topology edge leads directly to a screen owned by a peer.
fn clamped_remote_edge_delta(
    topology: &ScreenTopology,
    start: &PointerPosition,
    native_bounds: NativeScreenBounds,
    native_x: f64,
    native_y: f64,
    local_id: DeviceId,
) -> Option<(f64, f64)> {
    let first_x = f64::from(native_bounds.x);
    let first_y = f64::from(native_bounds.y);
    let last_x = first_x + f64::from(native_bounds.width.saturating_sub(1));
    let last_y = first_y + f64::from(native_bounds.height.saturating_sub(1));
    let candidates = [
        (native_x <= first_x, (-2.0, 0.0)),
        (native_x >= last_x, (2.0, 0.0)),
        (native_y <= first_y, (0.0, -2.0)),
        (native_y >= last_y, (0.0, 2.0)),
    ];

    candidates.into_iter().find_map(|(at_edge, delta)| {
        if !at_edge {
            return None;
        }
        let moved = topology
            .move_pointer_by(&start.screen_id, start.x, start.y, delta.0, delta.1)
            .ok()?;
        moved
            .transitions
            .iter()
            .any(|transition| {
                topology
                    .screen(&transition.to_screen_id)
                    .is_some_and(|screen| screen.owner_device_id != local_id)
            })
            .then_some(delta)
    })
}

fn drain_remote_releases(control: &mut ControlState) -> Vec<NativeInputEvent> {
    let mut releases = Vec::with_capacity(
        control.remote_pressed_keys.len() + control.remote_pressed_buttons.len(),
    );
    releases.extend(
        control
            .remote_pressed_keys
            .drain()
            .map(|code| NativeInputEvent::Key {
                code,
                pressed: false,
            }),
    );
    releases.extend(control.remote_pressed_buttons.drain().map(|button| {
        NativeInputEvent::PointerButton {
            button,
            pressed: false,
        }
    }));
    releases
}

fn config_path() -> Result<PathBuf, String> {
    let project = ProjectDirs::from("com", "InputMesh", "InputMesh")
        .ok_or_else(|| "无法确定用户配置目录".to_string())?;
    Ok(project.config_dir().join("config.json"))
}

fn os_version() -> String {
    #[cfg(target_os = "macos")]
    {
        std::process::Command::new("sw_vers")
            .arg("-productVersion")
            .output()
            .ok()
            .filter(|output| output.status.success())
            .and_then(|output| String::from_utf8(output.stdout).ok())
            .map(|version| version.trim().to_string())
            .filter(|version| !version.is_empty())
            .unwrap_or_else(|| "macOS".into())
    }
    #[cfg(target_os = "windows")]
    {
        "Windows".into()
    }
    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    {
        std::env::consts::OS.into()
    }
}

fn fingerprint(key: &[u8; 32]) -> String {
    let digest = Sha256::digest(key);
    digest[..16]
        .chunks(2)
        .map(|chunk| format!("{:02X}{:02X}", chunk[0], chunk[1]))
        .collect::<Vec<_>>()
        .join(" ")
}

fn parse_claim(claim_id: &str) -> Option<(u64, &str)> {
    let (generation, device_id) = claim_id.split_once(':')?;
    if device_id.is_empty() || claim_id.len() > 96 {
        return None;
    }
    Some((generation.parse().ok()?, device_id))
}

fn control_claim_is_stale(
    control: &ControlState,
    local_id: DeviceId,
    incoming_generation: u64,
    incoming_claim_id: &str,
) -> bool {
    // The startup generation is only a seed for the first physical-input
    // claim. Until that claim has actually been announced, it must not outrank
    // a peer that already has real input to deliver.
    if control.holder == local_id && !control.claim_announced {
        return false;
    }
    incoming_claim_id == control.lease_id
        || incoming_generation < control.generation
        || (incoming_generation == control.generation
            && incoming_claim_id < control.lease_id.as_str())
}

fn next_claim_generation(current: u64) -> u64 {
    current.saturating_add(1).max(unix_millis())
}

fn native_to_wire(event: NativeInputEvent, pressed_hid: &mut HashSet<u16>) -> Option<InputEvent> {
    match event {
        NativeInputEvent::PointerMoved { .. } => None,
        NativeInputEvent::PointerButton { button, pressed } => {
            let button = match button.as_str() {
                "Left" => PointerButton::Left,
                "Middle" => PointerButton::Middle,
                "Right" => PointerButton::Right,
                _ => return None,
            };
            Some(InputEvent::Button(ButtonInput {
                button,
                state: if pressed {
                    ButtonState::Pressed
                } else {
                    ButtonState::Released
                },
            }))
        }
        NativeInputEvent::Wheel { delta_x, delta_y } => Some(InputEvent::Wheel(WheelInput {
            delta_x: delta_x as f64,
            delta_y: delta_y as f64,
            unit: WheelUnit::Lines,
        })),
        NativeInputEvent::Key { code, pressed } => {
            let usage = key_name_to_hid(&code)?;
            let repeat = if pressed {
                !pressed_hid.insert(usage)
            } else {
                pressed_hid.remove(&usage);
                false
            };
            Some(InputEvent::Key(KeyInput {
                code: CanonicalKeyCode::Hid(HidKeyCode {
                    usage_page: 0x07,
                    usage,
                }),
                state: if pressed {
                    KeyState::Pressed
                } else {
                    KeyState::Released
                },
                repeat,
                modifiers: modifiers_from_pressed(pressed_hid),
            }))
        }
    }
}

fn update_pressed_keys_for_wire(event: &NativeInputEvent, pressed_hid: &mut HashSet<u16>) {
    if let NativeInputEvent::Key { code, pressed } = event
        && let Some(usage) = key_name_to_hid(code)
    {
        if *pressed {
            pressed_hid.insert(usage);
        } else {
            pressed_hid.remove(&usage);
        }
    }
}

fn modifiers_from_pressed(pressed: &HashSet<u16>) -> KeyModifiers {
    KeyModifiers {
        shift: pressed.contains(&0xe1) || pressed.contains(&0xe5),
        control: pressed.contains(&0xe0) || pressed.contains(&0xe4),
        alt: pressed.contains(&0xe2) || pressed.contains(&0xe6),
        meta: pressed.contains(&0xe3) || pressed.contains(&0xe7),
        caps_lock: pressed.contains(&0x39),
    }
}

fn validate_settings(settings: &SharingSettings) -> Result<(), String> {
    if settings.switch_delay_ms > 5_000 {
        return Err("切屏延迟不能超过 5000 ms".into());
    }
    if settings.edge_resistance_px > 200 {
        return Err("边缘阻力不能超过 200 px".into());
    }
    Ok(())
}

fn unix_millis() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
        .try_into()
        .unwrap_or(u64::MAX)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fingerprints_are_stable_and_readable() {
        assert_eq!(
            fingerprint(&[0; 32]),
            "6668 7AAD F862 BD77 6C8F C18B 8E9F 8E20"
        );
    }

    #[test]
    fn claim_parser_binds_generation_to_device() {
        assert_eq!(
            parse_claim("00000000000000000042:device"),
            Some((42, "device"))
        );
        assert_eq!(parse_claim("invalid"), None);
        assert_eq!(parse_claim("42:"), None);
    }

    #[test]
    fn unannounced_startup_seed_does_not_reject_a_real_remote_claim() {
        let local_id = Uuid::new_v4();
        let remote_id = Uuid::new_v4();
        let mut control = ControlState::new(local_id, None);
        control.generation = 200;
        control.lease_id = format!("{:020}:{local_id}", control.generation);
        let remote_claim = format!("{:020}:{remote_id}", 100);

        assert!(!control_claim_is_stale(
            &control,
            local_id,
            100,
            &remote_claim
        ));
        control.claim_announced = true;
        assert!(control_claim_is_stale(
            &control,
            local_id,
            100,
            &remote_claim
        ));
    }

    #[test]
    fn next_claim_generation_advances_past_observed_remote_values() {
        let current = unix_millis().saturating_add(10_000);
        assert_eq!(next_claim_generation(current), current + 1);
    }

    #[test]
    fn hid_modifiers_follow_physical_usages() {
        let pressed = HashSet::from([0xe0, 0xe5, 0xe7]);
        let modifiers = modifiers_from_pressed(&pressed);
        assert!(modifiers.control && modifiers.shift && modifiers.meta);
        assert!(!modifiers.alt);
    }

    #[test]
    fn first_key_press_is_not_marked_as_repeat() {
        let mut pressed = HashSet::new();
        let first = native_to_wire(
            NativeInputEvent::Key {
                code: "KeyA".into(),
                pressed: true,
            },
            &mut pressed,
        );
        let second = native_to_wire(
            NativeInputEvent::Key {
                code: "KeyA".into(),
                pressed: true,
            },
            &mut pressed,
        );
        assert!(matches!(
            first,
            Some(InputEvent::Key(KeyInput { repeat: false, .. }))
        ));
        assert!(matches!(
            second,
            Some(InputEvent::Key(KeyInput { repeat: true, .. }))
        ));
    }

    #[test]
    fn physical_pointer_motion_reclaims_control_even_when_priority_is_disabled() {
        let settings = SharingSettings {
            take_control_on_local_input: false,
            ..SharingSettings::default()
        };
        let pointer = NativeInputEvent::PointerMoved {
            x: 10.0,
            y: 20.0,
            delta_x: Some(0.0),
            delta_y: Some(0.0),
        };
        let key = NativeInputEvent::Key {
            code: "KeyA".into(),
            pressed: true,
        };

        assert!(local_input_can_reclaim_control(&pointer, &settings));
        assert!(!local_input_can_reclaim_control(&key, &settings));
    }

    #[test]
    fn slow_native_edge_motion_gets_one_pixel_of_topology_overshoot() {
        assert_eq!(native_edge_overshoot(1439.0, 0, 1440, 1.0), Some(2.0));
        assert_eq!(native_edge_overshoot(0.0, 0, 2560, -1.0), Some(-2.0));
        assert_eq!(native_edge_overshoot(1438.0, 0, 1440, 1.0), None);
        assert_eq!(native_edge_overshoot(1439.0, 0, 1440, -1.0), None);
    }

    #[test]
    fn clamped_windows_edge_recovers_only_toward_a_remote_neighbour() {
        let local_id = Uuid::new_v4();
        let remote_id = Uuid::new_v4();
        let make_screen = |id: &str, owner_device_id, x, y| ScreenInfo {
            id: id.into(),
            native_id: id.into(),
            owner_device_id,
            owner_name: id.into(),
            name: id.into(),
            width: 100,
            height: 100,
            scale_factor: 1.0,
            x,
            y,
            primary: id == "local",
            enabled: true,
            online: true,
        };
        let topology = ScreenTopology::new(vec![
            make_screen("local", local_id, 0, 0),
            make_screen("remote", remote_id, 0, 100),
        ])
        .unwrap();
        let bounds = NativeScreenBounds {
            x: 0,
            y: 0,
            width: 100,
            height: 100,
        };
        let start = PointerPosition::new("local", 50.0, 99.0);

        assert_eq!(
            clamped_remote_edge_delta(&topology, &start, bounds, 50.0, 99.0, local_id),
            Some((0.0, 2.0))
        );
        assert_eq!(
            clamped_remote_edge_delta(&topology, &start, bounds, 50.0, 50.0, local_id),
            None
        );
    }
}
